apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  labels:
    app: svc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc1
  template:
    metadata:
      labels:
        app: svc1
    spec:
      containers:
      - name: service1
        image: yashgoyal04/svc1:latest
        ports:
        - containerPort: 80
      
