apiVersion: v1
kind: Service
metadata:
  name: service2-service
spec:
  type: ClusterIP
  selector:
    app: svc2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 

---

apiVersion: v1
kind: Service
metadata:
  name: service1-service
spec:
  type: ClusterIP
  selector:
    app: svc1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 
